apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat3-ms-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soat3-ms-eureka
  template:
    metadata:
      labels:
        app: soat3-ms-eureka
    spec:
      containers:
        - name: soat3-ms-eureka
          image: franciscosviana/soat3-ms-eureka:v1
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: soat3-ms-eureka-service
spec:
  type: NodePort
  selector:
    app: soat3-ms-eureka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 32002